#Image with dependencies, named optifocal/dependencies
FROM python:3.7

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
#COPY . .

# install dependencies
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install CMake
RUN pip install dlib opencv-python numpy flask flask_socketio

# define the port number the container should expose
#EXPOSE 5000

# run the command
#CMD ["python", "./app.py"]
